import type { Metadata } from 'next';

import { generalSans } from '@/fonts';

import './globals.css';

export const metadata: Metadata = {
  title: 'Growchief',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: WithChildren) {
  return (
    <html lang="en" suppressHydrationWarning={true} className="scroll-smooth">
      <body className={`${generalSans.className} dark overflow-x-hidden w-full max-w-screen min-h-svh`}>
        {children}
      </body>
    </html>
  );
}
